#### Importing libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#### Loading and getting the first and last part of the data

In [2]:
ds=pd.read_csv("iris.csv")

In [3]:
ds.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
ds.tail(3)

sepal_length  sepal_width  petal_length  petal_width    species
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

#### Spliting the dependent and independent

In [5]:
x=ds.drop(['species'],axis=1)
y=ds['species'].values.reshape(-1,1)

#### Spliting the trainning and Testing data set

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

###### standardizing the data set

In [7]:

from sklearn.preprocessing import  StandardScaler
scal=StandardScaler()
scal.fit(x_train)
X_test=scal.transform(x_train)

#### Importing the KNN algorithm  and fitting

In [8]:

from sklearn.neighbors import KNeighborsClassifier
cls=KNeighborsClassifier(n_neighbors=5)
cls.fit(x_train,y_train)

C:\Users\Aravind\Anaconda3\envs\project\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [9]:
ypred=cls.predict(x_test)

In [10]:
print("enter the values:")
sl=float(input("Sepal length:-"))
sw=float(input("Sepal width:-"))
pl = float(input("petal_length : "))
pw=float(input("petal width:-"))
output=cls.predict([[sl,sw,pl,pw]])
print("the species is {}".format(output))


enter the values:
Sepal length:-5.0
Sepal width:-5.0
petal_length : 5.0
petal width:-5.0
the species is ['virginica']


In [11]:
from sklearn.metrics import  classification_report, confusion_matrix
print(classification_report(y_test, y_test))
print(confusion_matrix(y_test, y_test))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
